mod cpu;
mod debug;
mod log;
mod nes;
// mod nametable;
// mod oam;
mod palette;
mod pattern;
mod ppu;
// mod arecord;
// mod record;
mod rom;
mod screenshot;
mod view;

pub use self::log::LogView;
pub use cpu::CpuView;
pub use debug::DebugView;
// pub use nametable::NametableView;
// pub use oam::OamView;
pub use palette::PaletteView;
pub use pattern::PatternView;
pub use ppu::PpuView;
// pub use arecord::AudioRecordView;
// pub use record::RecordView;
pub use self::nes::NesView;
pub use rom::RomView;
pub use screenshot::ScreenshotView;
pub use view::View;
